name: CI Pipeline
on: [push, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version-file: ".java-version"

      - name: Build and test
        run: ./gradlew clean test
        continue-on-error: true

      - name: Lint
        run: ./gradlew check -x test
