name: CI
on:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install mise
        uses: jdx/mise-action@v4

      - name: Build and test
        run: ./gradlew clean test

      - name: Lint
        run: ./gradlew check -x test
